python -m colbert.scripts.train \
--model_name hltcoe/plaidx-large-zho-tdist-mt5xxl-engeng \
--training_triples /home/jju/datasets/hltcoe/t53b-monot5-msmarco-engeng.jsonl \
--training_irds_id neumarco/zh/train \
--maxsteps 10000 \
--learning_rate 5e-6 \
--kd_loss KLD \
--only_top \
--per_device_batch_size 8 \
--nway 6 \
--run_tag baseline \
--experiment colbert-full \
--other_args lite_query_encoder=True lite_document_encoder=False lite_num_hidden_layers=24 lite_num_attention_heads=16 lite_encoder_init=hltcoe/plaidx-large-zho-tdist-mt5xxl-engeng freeze_document_encoder=True
